name: Build and deploy to Azure Web App - wa-web-app1

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # или 7.0.x / 6.0.x под ваш проект

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8BC37F5730C448A687C6CBC63ADFAF0A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E5C230CEA52044FB8E3CE08249187F22 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_79C41568596143C08F209023D060CC2F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'wa-web-app1'
          slot-name: 'Production'
          package: publish
